name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: chekout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS


    - name: Build Docker Image
      run: |
        docker build -t dyrien7/docker-graphql:0.0.2 .
    - name: Push Docker Image
      run: |
        docker push dyrien7/docker-graphql:0.0.2
        
   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
